{
 "title": "Java JMX Metrics(KAFKA)",
 "tags": [
  "java",
  "jmx",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(up{job=~\"kafka-jmx\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status $instance",
   "type": "stat",
   "description": "Server Overview",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Process CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (java_lang_OperatingSystem_ProcessCpuLoad{instance=~\"$instance\", job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (java_lang_OperatingSystem_SystemCpuLoad{instance=~\"$instance\", job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Physical Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (1 - (java_lang_OperatingSystem_FreePhysicalMemorySize{instance=~\"$instance\", job=~\"$job\"} / java_lang_OperatingSystem_TotalPhysicalMemorySize{instance=~\"$instance\", job=~\"$job\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (1 - (java_lang_OperatingSystem_FreeSwapSpaceSize{instance=~\"$instance\", job=~\"$job\"} / java_lang_OperatingSystem_TotalSwapSpaceSize{instance=~\"$instance\", job=~\"$job\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Used"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_committed{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Committed"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Max"
    }
   ]
  },
  {
   "title": "Non-Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Used"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_committed{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Committed"
    }
   ]
  },
  {
   "title": "Memory Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"PS Eden Space\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Eden Space"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"PS Survivor Space\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Survivor Space"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"PS Old Gen\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Old Gen"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Metaspace\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Metaspace"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Compressed Class Space\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Compressed Class Space"
    },
    {
     "expr": "java_lang_MemoryPool_Usage_used{name=\"Code Cache\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Code Cache"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "GC Collection Count (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(java_lang_GarbageCollector_CollectionCount{name=\"PS Scavenge\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}} - Young GC Count"
    },
    {
     "expr": "increase(java_lang_GarbageCollector_CollectionCount{name=\"PS MarkSweep\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}} - Full GC Count"
    }
   ]
  },
  {
   "title": "GC Collection Time (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(java_lang_GarbageCollector_CollectionTime{name=\"PS Scavenge\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}} - Young GC Time"
    },
    {
     "expr": "increase(java_lang_GarbageCollector_CollectionTime{name=\"PS MarkSweep\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}} - Full GC Time"
    }
   ]
  },
  {
   "title": "Last Young GC Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_duration{name=\"PS Scavenge\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Last Full GC Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_duration{name=\"PS MarkSweep\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}"
    }
   ]
  },
  { "title": "Threads and Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_Threading_ThreadCount{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Current Threads"
    },
    {
     "expr": "java_lang_Threading_DaemonThreadCount{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Daemon Threads"
    },
    {
     "expr": "java_lang_Threading_PeakThreadCount{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Peak Threads"
    }
   ]
  },
  {
   "title": "Class Loading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_ClassLoading_LoadedClassCount{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Loaded Classes"
    },
    {
     "expr": "increase(java_lang_ClassLoading_TotalLoadedClassCount{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}} - Loaded Classes (1m)"
    },
    {
     "expr": "increase(java_lang_ClassLoading_UnloadedClassCount{cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}} - Unloaded Classes (1m)"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Direct Buffer Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_nio_BufferPool_MemoryUsed{name=\"direct\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Direct Buffer Memory Used"
    }
   ]
  },
  {
   "title": "Direct Buffer Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_nio_BufferPool_Count{name=\"direct\", cluster=~\"$cluster\", instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Direct Buffer Count"
    }
   ]
  }
 ]
}