global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "kafka-jmx"
    static_configs:
      - targets:
          - "jmxExporterController01:5556"
          - "jmxExporterController02:5556"
          - "jmxExporterBroker01:5556"
          - "jmxExporterBroker02:5556"
          - "jmxExporterBroker03:5556"
          - "Broker01Service:11001"
          - "Broker02Service:11001"
          - "Broker03Service:11001"
        labels:
          cluster: "kafka-cluster-1"

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "nodeExporter:9100"

  - job_name: "kminion"
    static_configs:
      - targets:
          - "kminion:8080"

  - job_name: "spring_boot_view_jmx"
    static_configs:
      - targets: ["host.docker.internal:9404"]

  - job_name: "spring_boot_api_jmx"
    static_configs:
      - targets: ["host.docker.internal:9405"]
